name: places
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  geolocator: ^7.0.3
  intl: ^0.17.0
  provider: ^5.0.0
  flutter_hooks: 0.16.0
  flutter_staggered_grid_view: ^0.4.0
  dio: ^4.0.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  build_runner: ^1.12.2
  mobx_codegen: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/fonts/
    - res/images/
    - res/images/category/
    - res/images/onboarding/