name: places
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  flutter_svg: ^0.19.2
  geolocator: ^6.1.14
  intl: 0.15.7
  provider: ^3.1.0
  flutter_hooks: 0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/fonts/
    - res/images/
    - res/images/category/
    - res/images/onboarding/